server:
  port: 6677


zookeeper:
  #zk连接地址
  address: 10.1.4.169:2181
  #用户名
  username:
  #密码
  password:
  # zk超时信息设置
  connection-timeout-ms: 5000
  # 会话超时时间，默认是20*tickTime
  session-timeout-ms: 5000
  #重试连接间隔：ms
  base-sleep-time-ms: 1000
  # 最大重试次数
  max-retries: 20

spring:
  datasource:
    #  驱动
    driver-class-name: org.h2.Driver
    # h2 内存数据库 内存模式连接配置 库名: main
    #url: jdbc:h2:mem:main
    # h2  嵌入模式连接  存储路径: E:/H2/yyzmain
    url: jdbc:h2:file:E:/H2/halo-next
    # 初始化数据表
    #schema: classpath:sql/init.sql
    password: 123456
    username: admin
  h2:
    console:
      #开启console 访问 默认false
      enabled: true
      settings:
        # 开启h2 console 跟踪 方便调试  默认 false
        trace: true
        # 允许console 远程访问 默认false
        web-allow-others: true
      # h2 访问路径上下文
      path: /h2-yyzmain

  kafka:
    bootstrap-servers: 192.168.88.129:9092
    consumer:
      group-id: cn-yyzmain
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 5
      session-timeout: 60000
      max-poll-interval-ms: 300000
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 1

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true